version: "3.9"
services:
  build-service-13:
    image: log-signing-mpc-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        N_OF_PARTIES: 3

  build-service-24:
    image: log-signing-mpc-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        N_OF_PARTIES: 4

  unit-tests:
    image: log-signing-mpc-image
    entrypoint: cargo test --release
