name: Build and Unit Tests

on: workflow_dispatch

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: log-signing-mpc-image

#    - name: Build the Docker image
#      run: docker compose build build-service
      
    - name: Run unit tests
      run: docker compose run unit-tests
