name: Log Signing MPC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag log-signing-mpc:$(date +%s)

    - name: Run unit tests
      run: docker run log-signing-mpc:$(date +%s) cargo test
