name: threshold-2-number-of-parties-4

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build the Docker image
        run: docker compose build build-service-24

      - name: Run servers
        run: docker-compose -f docker-compose-24.yml up

      - name: Wait for servers to start
        run: |
          retries=0
          max_retries=10
          while [[ $retries -lt $max_retries ]]; do
            sleep 5
            if curl --silent --head --fail http://la1:8001 && \
               curl --silent --head --fail http://la2:8002 && \
               curl --silent --head --fail http://la3:8003 && \
               curl --silent --head --fail http://la4:8004; then
              break
            fi
            retries=$((retries+1))
          done

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run API tests
        run: |
          pytest -k "TestKeyGen24 or TestSigning24 or TestVerify24 or TestPerformance24"

      - name: Clean up
        run: docker compose down
